#!/usr/bin/env node
// Generates `src/generated/inline-wasm.ts`: a TS module exporting the
// current `assets/ultrachess.wasm` as a base64 string.
//
// Consumers who `import { Chess } from "ultrachess/inline"` never need to
// fetch the .wasm file separately — it's decoded from the embedded string
// at module load. This trades ~33% bundle-size overhead (base64 vs raw)
// for synchronous instantiation that works in every runtime without
// top-level await or file I/O.

import { readFile, writeFile, mkdir } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const repo = resolve(here, "..");
const wasmPath = resolve(repo, "assets/ultrachess.wasm");
const outPath = resolve(repo, "src/generated/inline-wasm.ts");

const bytes = await readFile(wasmPath);
const base64 = bytes.toString("base64");

const banner = `// AUTO-GENERATED by scripts/generate-inline.mjs — do not edit by hand.\n`;
const body =
  `${banner}// Source: assets/ultrachess.wasm (${bytes.length} bytes).\n\n` +
  `/** Base64-encoded copy of ultrachess.wasm. */\n` +
  `export const WASM_BASE64 = "${base64}";\n\n` +
  `/** Decode into a fresh ArrayBuffer. Called once by ultrachess/inline. */\n` +
  `export function decodeWasm(): ArrayBuffer {\n` +
  `  // Node >=16, Deno, Bun, browsers all provide \`atob\`. For Node <16 users\n` +
  `  // the async entry is the sensible choice.\n` +
  `  const binary = atob(WASM_BASE64);\n` +
  `  const out = new Uint8Array(binary.length);\n` +
  `  for (let i = 0; i < binary.length; i++) out[i] = binary.charCodeAt(i);\n` +
  `  return out.buffer as ArrayBuffer;\n` +
  `}\n`;

await mkdir(dirname(outPath), { recursive: true });
await writeFile(outPath, body, "utf8");
console.log(
  `wrote ${outPath} (${bytes.length} bytes → ${base64.length} base64 chars)`,
);
